onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - core-js
  - esbuild
  - sharp

packages:
  - components/*
  - pages/*
  - plugins/*
  - hooks/*
  - netlify/functions/*
  - assets/*
  - types/*
